name: docs

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - name: '📥 Checkout repository'
        uses: actions/checkout@v1

      - name: '📸 Build Documentation'
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/v ]]; then
            tag="${GITHUB_REF/refs\/tags\//}"
          else
            tag=""
          fi
          ./scripts/update-docs.sh _build $tag
      - name: '📘 Publish'
        if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v') }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          enable_jekyll: false
          publish_dir: _build
          keep_files: true
